version: '3.9'

services:
  # Backend service
  opportune_frontend:
    build: .
    container_name: opportune_frontend
    ports: 
      # local->container
      - 4000:3000
    environment:
      PORT: 3000
      BACKEND_URL: "http://opportune_backend:3000"
    networks:
      - frontend

networks:
  frontend:
    name: opportune-frontend-network
    driver: bridge